### ISSUE TITLE
TypeError: 'range' object does not support item assignment

### ISSUE THREAD

**Issue by DarknightCanada** [nccgroup/demiguise#16]
Hey!

Keep getting this error

`Traceback (most recent call last):
  File "demiguise.py", line 126, in <module>
    hta_encrypted = base64.b64encode(rc4(args.key, hta_text))
  File "demiguise.py", line 87, in rc4
    S[i], S[j] = S[j], S[i]
TypeError: 'range' object does not support item assignment`

**Comment by DarknightCanada** [comment]
the issue was python2.7
